---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  kustomize.toolkit.fluxcd.io/name: staging-sj-cluster-infrastructure
  kustomize.toolkit.fluxcd.io/namespace: flux-system
fieldSpecs:
  - path: metadata/labels
    create: true
