---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  kustomize.toolkit.fluxcd.io/name: cluster-infrastructure-kubelet-serving-cert-approver
  kustomize.toolkit.fluxcd.io/namespace: flux-system
fieldSpecs:
  - path: metadata/labels
    create: true
