affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
deployment:
  annotations:
    reloader.stakater.com/auto: "true"
fullnameOverride: coredns
k8sAppLabelOverride: kube-dns
replicaCount: 2
servers:
  - plugins:
      - name: log
      - name: errors
      - configBlock: lameduck 5s
        name: health
      - configBlock: |-
          172.16.20.75 cluster-rpi.mesh.neilfren.ch
          10.0.1.150 cluster-sj.mesh.neilfren.ch
          129.146.165.14 gslb-ns-phx-neilfren-ch.neilfren.ch
          152.67.232.239 gslb-ns-sj-neilfren-ch.neilfren.ch
          76.87.29.142 gslb-ns-hb-neilfren-ch.neilfren.ch
          fallthrough
        name: hosts
      - name: ready
      - configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
    port: 53
    zones:
      - scheme: dns://
        use_tcp: true
        zone: .
service:
  clusterIP: 10.128.0.10
  name: kube-dns
serviceAccount:
  create: true
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: coredns
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
