---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  kustomize.toolkit.fluxcd.io/name: staging-sj-cluster-infrastructure
  kustomize.toolkit.fluxcd.io/prune: disabled
fieldSpecs:
  - kind: Namespace
    path: metadata/labels
